### ISSUE TITLE
Falla en python >= 3.2.3

### ISSUE THREAD

**Issue by mr-E** [mr-E/CFDiVigencia#1]
pySimpleSoap falla en version 3.4.3 (windows) y 3.2.3 (ubuntu), con este error:
## Ubuntu 3.2.3

``` quote
$pip-3.2 freeze
PySimpleSOAP==1.16

python3 CFDiVigencia.py 
Traceback (most recent call last):
  File "CFDiVigencia.py", line 106, in <module>
    servicio.verificaArchivos()
  File "CFDiVigencia.py", line 91, in verificaArchivos
    sat.get_estatus(self.__data)
  File "CFDiVigencia.py", line 34, in get_estatus
    client = SoapClient(wsdl=self._webservice)
  File "/usr/local/lib/python3.2/dist-packages/pysimplesoap/client.py", line 173, in __init__
    self.services = wsdl and self.wsdl_parse(wsdl, cache=cache)
  File "/usr/local/lib/python3.2/dist-packages/pysimplesoap/client.py", line 836, in wsdl_parse
    services = self._xml_tree_to_services(wsdl, cache, force_download)
  File "/usr/local/lib/python3.2/dist-packages/pysimplesoap/client.py", line 757, in _xml_tree_to_services
    for name, msg in op['fault_msgs'].iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
AttributeError: 'dict' object has no attribute 'iteritems'
```
## Windows 8.1 32 bits Python 3.4.3

``` quote
pip freeze
arrow==0.5.4
moment==0.2.2
pygubu==0.9.7
PySimpleSOAP==1.16
python-dateutil==2.4.1
pytz==2014.10
pywin32==219
selenium==2.45.0
six==1.9.0
soap2py==1.16
times==0.7

Running: H:\Devel\python\XMLviewBeta\CFDiVigencia.py (Fri Mar 20 14:43:44 2015)
Traceback (most recent call last):
  File "H:\Devel\python\XMLviewBeta\CFDiVigencia.py", line 106, in <module>
    servicio.verificaArchivos()
  File "H:\Devel\python\XMLviewBeta\CFDiVigencia.py", line 91, in verificaArchivos
    sat.get_estatus(self.__data)
  File "H:\Devel\python\XMLviewBeta\CFDiVigencia.py", line 34, in get_estatus
    client = SoapClient(wsdl=self._webservice)
  File "C:\Python34\lib\site-packages\pysimplesoap\client.py", line 173, in __init__
    self.services = wsdl and self.wsdl_parse(wsdl, cache=cache)
  File "C:\Python34\lib\site-packages\pysimplesoap\client.py", line 836, in wsdl_parse
    services = self._xml_tree_to_services(wsdl, cache, force_download)
  File "C:\Python34\lib\site-packages\pysimplesoap\client.py", line 757, in _xml_tree_to_services
    for name, msg in op['fault_msgs'].iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by mr-E** [comment]
Con la corrección propuesta:
https://github.com/pysimplesoap/pysimplesoap/pull/52
Puedo continuar usando pysimplesoap en Python3
